import type { Offer } from './types';

export const mockOffers: Offer[] = [
  {
    id: '1',
    title: '2-for-1 Artisanal Coffee',
    description: 'Buy one handcrafted coffee and get the second one free. Perfect for a morning boost.',
    fullDescription: 'Start your day right at The Daily Grind. We are offering a special 2-for-1 deal on all our artisanal coffees. Whether you prefer a classic espresso, a creamy latte, or a bold pour-over, you and a friend can enjoy our expertly crafted beverages. This offer is valid Monday to Friday, from 7 AM to 11 AM.',
    companyName: 'The Daily Grind',
    latitude: 37.7749,
    longitude: -122.4194,
    isMemberOnly: false,
    distance: '0.2 mi',
    discount: 'BOGO',
  },
  {
    id: '2',
    title: '50% Off First Month of Yoga',
    description: 'New members get 50% off their first month of unlimited yoga classes.',
    fullDescription: 'Find your inner peace and build your strength at Serenity Yoga Studio. We believe in the transformative power of yoga and want to make it accessible to everyone. As a new member, you\'ll receive a 50% discount on your first month of unlimited classes. Explore various styles from Vinyasa to Yin with our experienced instructors.',
    companyName: 'Serenity Yoga Studio',
    latitude: 37.785,
    longitude: -122.425,
    isMemberOnly: true,
    distance: '0.8 mi',
    discount: '50% OFF',
  },
  {
    id: '3',
    title: 'Free Appetizer with Entree',
    description: 'Enjoy a complimentary appetizer with the purchase of any main entree.',
    fullDescription: 'Experience authentic Italian cuisine at Bella\'s Trattoria. Our chefs use only the freshest ingredients to bring the taste of Italy to your table. For a limited time, receive a free appetizer of your choice (up to $15 value) with the purchase of any entree. Buon appetito!',
    companyName: 'Bella\'s Trattoria',
    latitude: 37.77,
    longitude: -122.41,
    isMemberOnly: false,
    distance: '1.1 mi',
    discount: 'FREE',
  },
  {
    id: '4',
    title: '25% Off All Books',
    description: 'Expand your library with a 25% discount on our entire collection of new and used books.',
    fullDescription: 'Get lost in a world of stories at The Book Nook. We are an independent bookstore with a passion for literature. To celebrate our community, we are offering a 25% discount on all books in the store. From bestsellers to hidden gems, find your next great read with us.',
    companyName: 'The Book Nook',
    latitude: 37.79,
    longitude: -122.43,
    isMemberOnly: false,
    distance: '1.5 mi',
    discount: '25% OFF',
  },
  {
    id: '5',
    title: 'VIP Shopping Experience',
    description: 'Members get a private styling session and an exclusive 30% discount.',
    fullDescription: 'Elevate your style with a VIP experience at "Chic Boutique". As a valued member, you are invited for a complimentary private styling session with one of our fashion experts. During your session, enjoy an exclusive 30% discount on your entire purchase. Book your appointment today!',
    companyName: 'Chic Boutique',
    latitude: 37.765,
    longitude: -122.42,
    isMemberOnly: true,
    distance: '1.8 mi',
    discount: '30% OFF',
  },
  {
    id: '6',
    title: 'Free Scoop of Ice Cream',
    description: 'Get a free scoop of your favorite flavor with any purchase over $5.',
    fullDescription: 'Cool down with a sweet treat from "Scoops Ahoy". We make our ice cream in-house with locally sourced ingredients. When you spend $5 or more, you get a free scoop on us! Choose from over 20 unique and delicious flavors.',
    companyName: 'Scoops Ahoy',
    latitude: 37.78,
    longitude: -122.405,
    isMemberOnly: false,
    distance: '2.2 mi',
    discount: 'FREE',
  },
];
