
import { ROLES } from '@/constants/auth.constant';

export type NavPermission =
	| '*'
	| 'DASHBOARD'
	| 'REQUESTS_MENU'
	| 'REQUESTS_LIST'
	| 'REQUESTS_NEW'
	| 'REQUESTS_PENDING'
	| 'REQUESTS_PROCESSING'
	| 'REQUESTS_COMPLETED'
	| 'APPLICATIONS'
	| 'APPLICATIONS_PENDING'
	| 'APPLICATIONS_PROCESSING'
	| 'APPLICATIONS_SHORTLISTED'
	| 'JOBSEEKERS'
	| 'CLIENT_ORGANIZATIONS'
	| 'USER_MANAGEMENT'
	| 'MASTER_DATA'
	| 'MASTER_DATA_ORG_TYPES'
	| 'MASTER_DATA_POSTS'
	| 'MASTER_DATA_SKILLS'
	| 'MASTER_DATA_LANGUAGES'
	| 'MASTER_DATA_EDUCATION'
	| 'MASTER_DATA_EDUCATION_DEGREE_LEVELS'
	| 'MASTER_DATA_EDUCATION_DEGREES'
	| 'MASTER_DATA_EDUCATION_INSTITUTIONS'
	| 'MASTER_DATA_TRAINING'
	| 'MASTER_DATA_TRAINING_CERTIFICATIONS'
	| 'MASTER_DATA_OUTSOURCING'
	| 'MASTER_DATA_OUTSOURCING_CATEGORY'
	| 'MASTER_DATA_OUTSOURCING_ZONE'
	| 'MASTER_DATA_OUTSOURCING_CHARGE'
	| 'MASTER_DATA_ATTACHMENTS';

export const rolePermissions: Record<ROLES, { allow?: NavPermission[]; notAllow?: NavPermission[] }> = {
	[ROLES.SUPER_ADMIN]: {
		allow: ['*'], // Wildcard for all permissions
	},
	[ROLES.ADMIN]: {
		notAllow: [
			'REQUESTS_LIST',
			'MASTER_DATA_ORG_TYPES',
			'MASTER_DATA_SKILLS',
			'MASTER_DATA_LANGUAGES',
			'MASTER_DATA_EDUCATION',
			'MASTER_DATA_TRAINING',
			'MASTER_DATA_OUTSOURCING',
		],
	},
	[ROLES.OPERATOR]: {
		allow: [
			'DASHBOARD',
			'REQUESTS_NEW',
			'REQUESTS_PROCESSING',
			'APPLICATIONS_PENDING',
			'APPLICATIONS_PROCESSING',
			'JOBSEEKERS',
		],
	},
	[ROLES.USER]: {
		// This is for jobseeker roles, handled separately but good to have.
	},
};
